# Generated by Django 5.0.1 on 2024-01-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0002_rename_customer_loan_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
