# Generated by Django 5.0.1 on 2024-01-23 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0003_alter_loan_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_app.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(),
        ),
    ]
