# Generated by Django 5.0.1 on 2024-01-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0004_remove_loan_customer_id_loan_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.FloatField(null=True),
        ),
    ]
