# Generated by Django 5.0.1 on 2024-01-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0005_alter_customer_approved_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
