# Generated by Django 5.0.1 on 2024-01-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0006_alter_customer_approved_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
